/**
 * Shared Scoring Validation & Schema for PenShift AI Stylometry Detection.
 * Enforces strict boundaries, rejecting malformed JSON, missing fields, and out-of-range values.
 */

export const SCORING_SYSTEM_PROMPT = `You are an expert AI stylometry and forensic text analyzer.
Your task is to analyze the provided text and evaluate whether it was written by a human or generated by an AI model.

Analyze the following 5 stylometric signals (each scored 0 to 20, where higher indicates human-like and lower indicates AI-like):
1. sentenceVariation (0-20): sentence length variance, clause diversity, and syntactical rhythm
2. vocabularyDiversity (0-20): richness of vocabulary, avoiding AI buzzwords and repetitive phrasing
3. burstiness (0-20): mix of short punchy clauses and long complex sentences
4. predictability (0-20): statistical word predictability (high predictability indicates AI, unexpected word choice indicates human)
5. structureRandomness (0-20): organic transitions vs rigid, formulaic paragraph structure

Calculate:
- humanScore (0-100): aggregate human authenticity percentage
- aiScore (0-100): aggregate AI generation probability (aiScore must equal 100 - humanScore)
- breakdown: object containing sentenceVariation, vocabularyDiversity, burstiness, predictability, structureRandomness (each 0-20)
- signals: object with brief observation strings for each signal
- reasoning: array of 2-3 specific analytical observations

Respond ONLY with a valid JSON object matching this exact schema:
{
  "humanScore": <number 0-100>,
  "aiScore": <number 0-100>,
  "breakdown": {
    "sentenceVariation": <number 0-20>,
    "vocabularyDiversity": <number 0-20>,
    "burstiness": <number 0-20>,
    "predictability": <number 0-20>,
    "structureRandomness": <number 0-20>
  },
  "signals": {
    "sentenceVariation": "<observation>",
    "vocabularyDiversity": "<observation>",
    "burstiness": "<observation>",
    "predictability": "<observation>",
    "structureRandomness": "<observation>"
  },
  "reasoning": ["<point 1>", "<point 2>"]
}`;

export function buildScoringUserPrompt(text) {
  const boundedText = typeof text === 'string' ? text.slice(0, 40000) : JSON.stringify(text);
  return `Analyze this text for AI stylometry:\n\n<text_to_analyze>\n${boundedText}\n</text_to_analyze>`;
}

export function validateScoringResult(data) {
  if (!data || typeof data !== 'object' || Array.isArray(data)) {
    return { valid: false, reason: 'Scoring result must be a non-null object' };
  }

  const { humanScore, aiScore, breakdown, signals, reasoning } = data;

  if (typeof humanScore !== 'number' || Number.isNaN(humanScore) || humanScore < 0 || humanScore > 100) {
    return { valid: false, reason: `humanScore must be a number between 0 and 100, received: ${humanScore}` };
  }

  if (typeof aiScore !== 'number' || Number.isNaN(aiScore) || aiScore < 0 || aiScore > 100) {
    return { valid: false, reason: `aiScore must be a number between 0 and 100, received: ${aiScore}` };
  }

  if (!breakdown || typeof breakdown !== 'object' || Array.isArray(breakdown)) {
    return { valid: false, reason: 'breakdown must be an object' };
  }

  const requiredBreakdownKeys = [
    'sentenceVariation',
    'vocabularyDiversity',
    'burstiness',
    'predictability',
    'structureRandomness',
  ];

  for (const key of requiredBreakdownKeys) {
    const val = breakdown[key];
    if (typeof val !== 'number' || Number.isNaN(val) || val < 0 || val > 20) {
      return { valid: false, reason: `breakdown.${key} must be a number between 0 and 20, received: ${val}` };
    }
  }

  const cleanedSignals = signals && typeof signals === 'object' && !Array.isArray(signals) ? signals : {};
  const cleanedReasoning = Array.isArray(reasoning) ? reasoning.map((r) => String(r)).slice(0, 5) : [];

  return {
    valid: true,
    result: {
      humanScore: Math.round(humanScore),
      aiScore: Math.round(aiScore),
      breakdown: {
        sentenceVariation: Math.round(breakdown.sentenceVariation),
        vocabularyDiversity: Math.round(breakdown.vocabularyDiversity),
        burstiness: Math.round(breakdown.burstiness),
        predictability: Math.round(breakdown.predictability),
        structureRandomness: Math.round(breakdown.structureRandomness),
      },
      signals: cleanedSignals,
      reasoning: cleanedReasoning,
    },
  };
}
